import React, { Component } from 'react';

class MemeGenerator extends Component {
  constructor() {
    super();
    this.state = {
      topText: '',
      bottomText: '',
      randomImage: 'http://i.imgflip.com/1bij.jpg',
      allMemeImgs: [],
    };
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  componentDidMount() {
    fetch('https://api.imgflip.com/get_memes')
      .then((response) => response.json())
      .then((data) => {
        const { memes } = data.data;
        console.log(memes[0]);
        this.setState({
          allMemeImgs: memes,
        });
      });
  }

  handleChange(event) {
    const { name, value } = event.target;
    this.setState({ [name]: value });
  }

  handleSubmit(event) {
    event.preventDefault();
    // get random int (index in the array)
    const randNum = Math.floor(Math.random() * this.state.allMemeImgs.length);
    // get meme url from the random index number generated by const random
    const randMemeImg = this.state.allMemeImgs[randNum].url;
    // update randomImg with the new image
    this.state({ randomImage: randMemeImg });
  }

  render() {
    return (
      <div>
        <form className="meme-form" onSubmit={this.handleSubmit}>
          <input
            type="text"
            name="topText"
            placeholder="Top Text"
            value={this.state.topText}
            onChange={this.handleChange}
          />
          <br />
          <input
            type="text"
            name="bottomText"
            placeholder="Bottom Text"
            value={this.state.bottomText}
            onChange={this.handleChange}
          />
          <br />
          <button>Gen</button>
        </form>
        <div className="meme">
          <img src={this.state.randomImage} alt="random meme image" />
          <h2 className="top">{this.state.topText}</h2>
          <h2 classNAme="bottom">{this.state.bottomText}</h2>
        </div>
      </div>
    );
  }
}

export default MemeGenerator;
